version: '3.2'

services:
  www-public:
    image: website/www-public:latest
    container_name: website-gatsby
    build:
      context: ./
      dockerfile: dockerfile
    env_file: 
      - ./website/.env.development
    ports:
      - "8000:8000"
    networks: 
      - website-net
    volumes: 
      - ./:/root/dev/
      - type: volume
        source: website-dependencies
        target: /root/dev/web/node_modules
        volume:
          nocopy: true
    # extra_hosts:
    #   - "www:0.0.0.0"

  

networks: 
  pl-net:
    driver: bridge

volumes:
  www-dependencies:
  api: